version: '3.9'

networks:
  reseau-internet:
    driver: bridge
    ipam:
      config:
        - subnet: 172.31.0.0/24

  reseau-central:
    driver: bridge
    ipam:
      config:
        - subnet: 172.30.100.0/24

  reseau-rd:
    driver: bridge
    ipam:
      config:
        - subnet: 172.30.1.0/24

  reseau-rh:
    driver: bridge
    ipam:
      config:
        - subnet: 172.30.2.0/24

  reseau-com:
    driver: bridge
    ipam:
      config:
        - subnet: 172.30.3.0/24

  reseau-outils:
    driver: bridge
    ipam:
      config:
        - subnet: 172.30.4.0/24

services:
  # Client distant (simulateur de connexion VPN)
  pc-remote:
    image: alpine
    container_name: pc-remote
    command: sleep infinity
    networks:
      reseau-internet:
        ipv4_address: 172.31.0.10

  # Routeur internet (RI)
  routeur-ri:
    image: alpine
    container_name: routeur-ri
    command: sleep infinity
    cap_add:
      - NET_ADMIN
    networks:
      reseau-internet:
        ipv4_address: 172.31.0.254
      reseau-central:
        ipv4_address: 172.30.100.254

  # Routeur central (RC)
  routeur-rc:
    image: alpine
    container_name: routeur-rc
    command: sleep infinity
    cap_add:
      - NET_ADMIN
    networks:
      reseau-central:
        #ipv4_address: 172.30.100.2
      reseau-rd:
        #ipv4_address: 172.30.1.254
      reseau-rh:
        #ipv4_address: 172.30.2.254
      reseau-com:
        #ipv4_address: 172.30.3.254
      reseau-outils:
        #ipv4_address: 172.30.4.254

  # Routeur R&D
  routeur-rd:
    image: alpine
    container_name: routeur-rd
    command: sleep infinity
    cap_add:
      - NET_ADMIN
    networks:
      reseau-rd:
        ipv4_address: 172.30.1.253

  pc1:
    image: alpine
    container_name: pc1
    command: sleep infinity
    networks:
      reseau-rd:
        ipv4_address: 172.30.1.10

  pc2:
    image: alpine
    container_name: pc2
    command: sleep infinity
    networks:
      reseau-rd:
        ipv4_address: 172.30.1.11

  # Routeur RH
  routeur-rh:
    image: alpine
    container_name: routeur-rh
    command: sleep infinity
    cap_add:
      - NET_ADMIN
    networks:
      reseau-rh:
        ipv4_address: 172.30.2.253

  pc3:
    image: alpine
    container_name: pc3
    command: sleep infinity
    networks:
      reseau-rh:
        ipv4_address: 172.30.2.10

  pc4:
    image: alpine
    container_name: pc4
    command: sleep infinity
    networks:
      reseau-rh:
        ipv4_address: 172.30.2.11

  # Routeur Communication
  routeur-com:
    image: alpine
    container_name: routeur-com
    command: sleep infinity
    cap_add:
      - NET_ADMIN
    networks:
      reseau-com:
        ipv4_address: 172.30.3.253

  pc5:
    image: alpine
    container_name: pc5
    command: sleep infinity
    networks:
      reseau-com:
        ipv4_address: 172.30.3.10

  pc6:
    image: alpine
    container_name: pc6
    command: sleep infinity
    networks:
      reseau-com:
        ipv4_address: 172.30.3.11

  # Routeur Outils (VPN/IDS/IPS/admin à venir)
  routeur-outils:
    image: alpine
    container_name: routeur-outils
    command: sleep infinity
    cap_add:
      - NET_ADMIN
    networks:
      reseau-outils:
        ipv4_address: 172.30.4.253

