version: '3.9'

networks:
  reseau-internet:
    driver: bridge
    ipam:
      config:
        - subnet: 172.31.0.0/24

  reseau-central:
    driver: bridge
    ipam:
      config:
        - subnet: 172.30.100.0/24

  reseau-rh:
    driver: bridge
    ipam:
      config:
        - subnet: 172.30.2.0/24

  reseau-com:
    driver: bridge
    ipam:
      config:
        - subnet: 172.30.3.0/24

  reseau-outils:
    driver: bridge
    ipam:
      config:
        - subnet: 172.30.4.0/24

services:
  routeur-ri:
    build:
      context: .
      dockerfile: Dockerfile.routeur
    container_name: routeur-ri
    cap_add:
      - NET_ADMIN
    privileged: true
    networks:
      reseau-internet:
        ipv4_address: 172.31.0.254
      reseau-central:
        ipv4_address: 172.30.100.254

  routeur-rc:
    build:
      context: .
      dockerfile: Dockerfile.routeur
    container_name: routeur-rc
    cap_add:
      - NET_ADMIN
    privileged: true
    networks:
      reseau-central:
        ipv4_address: 172.30.100.2
      reseau-rh:
        ipv4_address: 172.30.2.2
      reseau-com:
        ipv4_address: 172.30.3.2
      reseau-outils:
        ipv4_address: 172.30.4.2

  routeur-rh:
    build:
      context: .
      dockerfile: Dockerfile.routeur
    container_name: routeur-rh
    cap_add:
      - NET_ADMIN
    privileged: true
    networks:
      reseau-rh:
        ipv4_address: 172.30.2.253

  routeur-com:
    build:
      context: .
      dockerfile: Dockerfile.routeur
    container_name: routeur-com
    cap_add:
      - NET_ADMIN
    privileged: true
    networks:
      reseau-com:
        ipv4_address: 172.30.3.253

  routeur-outils:
    build:
      context: .
      dockerfile: Dockerfile.routeur
    container_name: routeur-outils
    cap_add:
      - NET_ADMIN
    privileged: true
    networks:
      reseau-outils:
        ipv4_address: 172.30.4.253
        
  pc1:
    image: alpine
    container_name: pc1
    command: sleep infinity
    cap_add:
    - NET_ADMIN
    networks:
      reseau-rh:
        ipv4_address: 172.30.2.10

  pc2:
    image: alpine
    container_name: pc2
    command: sleep infinity
    cap_add:
    - NET_ADMIN
    networks:
      reseau-com:
        ipv4_address: 172.30.3.10

  pc-remote:
    image: alpine
    container_name: pc-remote
    command: sleep infinity
    cap_add:
    - NET_ADMIN
    networks:
      reseau-internet:
        ipv4_address: 172.31.0.10
